# Generated by Django 4.0.3 on 2022-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gamer',
            field=models.CharField(default='@gamer', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Hyrule', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='In the Grass behind the castle'),
            preserve_default=False,
        ),
    ]
