# Generated by Django 4.0.3 on 2022-03-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_gamer_post_location_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='game',
        ),
    ]
